In [21]:
from array import *
def array_list(array_num):
    num_list = array_num.tolist()
    print(num_list)
array_num = array('i', [45,34,67])
array_list(array_num)

[45, 34, 67]


In [27]:
n_array = np.array([[5, 2, 1],
                    [3,40,22],
                    [1,33,20]])
print("numpy matrix is : ")
print(n_array)
trace = np.trace(n_array)
print("trace of given 3X3 matrix")
print(trace)

numpy matrix is : 
[[ 5  2  1]
 [ 3 40 22]
 [ 1 33 20]]
trace of given 3X3 matrix
65


In [36]:
x = np.array([[11, 3, 4], [3, 20, 30]])
print("Original array ")
print(x)
print("Values bigger than 10 = ", x[x>10])
print("Their indices are ", np.nonzero(x > 10))

Original array 
[[11  3  4]
 [ 3 20 30]]
Values bigger than 10 =  [11 20 30]
Their indices are  (array([0, 1, 1]), array([0, 1, 2]))


In [45]:
A = np.array([[3, 10, 16], [27, 13, 9], [100, 11, 30]])
B = np.random.randint(22, 100, size=(3,3))
print(A)
print(B)
C = A+B
print("la somme des deux array est :")
print(C)

[[  3  10  16]
 [ 27  13   9]
 [100  11  30]]
[[67 65 83]
 [99 84 99]
 [92 62 72]]
la somme des deux array est :
[[ 70  75  99]
 [126  97 108]
 [192  73 102]]


In [64]:
w = np.random.random((3, 3))
print(w)
w_mean = np.mean(w, axis=1)
print("la moyenne des lignes est :")
print(w_mean)


[[0.37010916 0.65825428 0.03727986]
 [0.60208898 0.55152964 0.44068642]
 [0.24181914 0.93569932 0.68468191]]
la moyenne des lignes est 
[0.35521443 0.53143501 0.62073346]
